import { compilePresentation } from './presentation.mjs';
import { narrative, validateScenes, references } from './script.mjs';
export function assemble(project) {
  const compiled = compilePresentation(project), scenes = {}, sourceMap = [], graph = [];
  const names = new Set();
  for (const chapter of project.chapters) {
    if (!/^[A-Za-z][A-Za-z0-9_-]*$/.test(chapter.id) || names.has(chapter.id) || !chapter.beats.length) throw Error(`Invalid or duplicate chapter ${chapter.id}`);
    names.add(chapter.id);
  }
  if (project.checkpoints && project.chapters.length > 8) throw Error('Native checkpoint profile supports at most eight chapters');
  const beatMap = new Map(compiled.beats.map(b => [b.id, b]));
  scenes['start.txt'] = [`changeScene:${project.chapters[0].id}.txt;`];
  let checkpoint = 0;
  for (const [i, chapter] of project.chapters.entries()) {
    const name = chapter.id + '.txt';
    const lines = ['; Generated by WebGAL-Production-Kit', `setVar:_vn_chapter=${i + 1};`];
    if (i === 0) lines.push('setVar:_release_checkpoint=0;', 'setVar:_release_open_load=0;', 'setVar:_release_news=0;', 'setVar:_release_credits=0;');
    for (const beat of chapter.beats) {
      const row = beatMap.get(beat.id), start = lines.length + 1;
      lines.push(...row.lines); sourceMap.push({ beat: beat.id, sourceHash: row.sourceHash, scene: name, startLine: start, endLine: lines.length, state: row.state });
    }
    if (project.checkpoints) {
      checkpoint++;
      lines.push(`setVar:_release_checkpoint=${checkpoint};`, 'choose:章节自动存档中:_production_checkpoint_resume;', 'label:_production_checkpoint_resume;', 'setVar:_release_checkpoint=0;');
    }
    const next = project.chapters[i + 1];
    lines.push(next ? `changeScene:${next.id}.txt;` : project.credits?.length ? 'changeScene:credits.txt;' : 'end;');
    scenes[name] = lines;
  }
  if (project.credits?.length) scenes['credits.txt'] = ['setVar:_release_news=0;', 'setVar:_release_credits=1;', 'changeFigure:;', ...Object.keys(project.characters ?? {}).map(id => `changeFigure: -id=${id} -duration=0;`), ...project.credits, 'end;'];
  validateScenes(scenes);
  for (const [name, lines] of Object.entries(scenes)) graph.push({ scene: name, next: references(lines).scenes });
  const actual = project.chapters.flatMap(c => scenes[c.id + '.txt'].filter(l => narrative(l)));
  if (JSON.stringify(actual) !== JSON.stringify(compiled.narrative)) throw Error('Chapter split lost or duplicated narrative');
  return { ...compiled, scenes, report: { schemaVersion: 1, scenes: Object.keys(scenes).length, chapters: project.chapters.length, narrativeLines: actual.length, checkpoints: checkpoint, narrativeInvariant: true, assets: compiled.assets, displayChanges: compiled.displayChanges, graph, sourceMap } };
}
