import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { auditIndex } from '../tools/audit-source.mjs';
import { inventory } from '../tools/verify-game.mjs';
import { ownedPath } from '../src/files.mjs';
import { validateScenes } from '../src/script.mjs';
const kit=fileURLToPath(new URL('..',import.meta.url));
const original=JSON.parse(fs.readFileSync(path.join(kit,'examples/demo/project.json'),'utf8'));
const run=(tool,...args)=>execFileSync(process.execPath,[path.join(kit,'tools',tool),...args],{cwd:kit,encoding:'utf8',windowsHide:true,stdio:'pipe'});
function fixture(fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'webgal-production-test-'));try{return fn(dir);}finally{assert.equal(path.dirname(dir),os.tmpdir());fs.rmSync(dir,{recursive:true,force:true});}}
function manifest(dir,p=original){const file=path.join(dir,'project.json');fs.writeFileSync(file,JSON.stringify(p));return file;}
test('CLI blocks anchor drift and only accepts it with an explicit flag',()=>fixture(dir=>{const file=manifest(dir),out=path.join(dir,'build');run('build.mjs',file,'--out',out);const before=fs.readFileSync(path.join(out,'game/scene/chapter01.txt'),'utf8');const p=structuredClone(original);p.chapters[0].beats[0].lines[0]=':修改后的示例。;';manifest(dir,p);assert.throws(()=>run('build.mjs',file,'--out',out),/anchors changed/);assert.equal(fs.readFileSync(path.join(out,'game/scene/chapter01.txt'),'utf8'),before);run('build.mjs',file,'--out',out,'--accept-anchors');assert.ok(fs.readFileSync(path.join(out,'game/scene/chapter01.txt'),'utf8').includes('修改后的示例'));}));
test('managed rebuild removes a deleted scene and leaves unrelated files intact',()=>fixture(dir=>{const file=manifest(dir),out=path.join(dir,'build');run('build.mjs',file,'--out',out);fs.writeFileSync(path.join(out,'keep.txt'),'keep');const p=structuredClone(original);p.credits=[];manifest(dir,p);run('build.mjs',file,'--out',out);assert.equal(fs.existsSync(path.join(out,'game/scene/credits.txt')),false);assert.equal(fs.readFileSync(path.join(out,'keep.txt'),'utf8'),'keep');}));
test('build refuses a populated unmanaged directory before changing any files',()=>fixture(dir=>{const file=manifest(dir),out=path.join(dir,'build');fs.mkdirSync(out);fs.writeFileSync(path.join(out,'keep.txt'),'keep');assert.throws(()=>run('build.mjs',file,'--out',out),/unmanaged/);assert.deepEqual(fs.readdirSync(out),['keep.txt']);}));
test('tainted owned-file inventory cannot remove anything outside the build',()=>fixture(dir=>{const file=manifest(dir),out=path.join(dir,'build');run('build.mjs',file,'--out',out);fs.writeFileSync(path.join(dir,'outside.txt'),'keep');fs.writeFileSync(path.join(out,'owned-files.json'),JSON.stringify(['../outside.txt']));assert.throws(()=>run('build.mjs',file,'--out',out),/Unsafe owned/);assert.equal(fs.readFileSync(path.join(dir,'outside.txt'),'utf8'),'keep');assert.throws(()=>ownedPath(out,'a/../outside'));}));
test('installation restores overwritten files and removes only newly installed files',()=>fixture(dir=>{const file=manifest(dir),out=path.join(dir,'build'),dist=path.join(dir,'dist');run('build.mjs',file,'--out',out);fs.mkdirSync(path.join(dist,'game/scene'),{recursive:true});fs.writeFileSync(path.join(dist,'index.html'),'<head></head>');fs.writeFileSync(path.join(dist,'game/config.txt'),'original config');fs.writeFileSync(path.join(dist,'game/scene/start.txt'),':original;');fs.writeFileSync(path.join(dist,'game/keep.txt'),'unrelated');run('install.mjs',out,dist);assert.throws(()=>run('install.mjs',out,dist),/Restore/);run('install.mjs',out,dist,'--restore');assert.equal(fs.readFileSync(path.join(dist,'game/config.txt'),'utf8'),'original config');assert.equal(fs.readFileSync(path.join(dist,'game/scene/start.txt'),'utf8'),':original;');assert.equal(fs.existsSync(path.join(dist,'game/scene/chapter01.txt')),false);assert.equal(fs.readFileSync(path.join(dist,'game/keep.txt'),'utf8'),'unrelated');}));
test('game verification checks reachable scenes and does not score unused upstream examples',()=>fixture(dir=>{const dist=path.join(dir,'dist');fs.mkdirSync(path.join(dist,'game/scene'),{recursive:true});fs.writeFileSync(path.join(dist,'game/scene/start.txt'),'changeScene:chapter.txt;');fs.writeFileSync(path.join(dist,'game/scene/chapter.txt'),':example;\nend;');fs.writeFileSync(path.join(dist,'game/scene/unreachable.txt'),'jumpLabel:missing;');const report=JSON.parse(run('verify-game.mjs',dist));assert.equal(report.scenes,2);fs.writeFileSync(path.join(dist,'game/scene/chapter.txt'),'jumpLabel:missing;');assert.throws(()=>run('verify-game.mjs',dist),/unresolved/);}));
test('native scene choices and trailing choice parameters validate correctly',()=>{validateScenes({'start.txt':['choose:下一场:next.txt;'],'next.txt':['choose:继续:local -defaultChoose=1;','label:local;','end;']});});
test('game packaging mirrors every source hash, preserves license and refuses existing output',()=>fixture(dir=>{const dist=path.join(dir,'dist'),out=path.join(dir,'release');fs.mkdirSync(path.join(dist,'game/scene'),{recursive:true});fs.writeFileSync(path.join(dist,'index.html'),'<head></head>');fs.writeFileSync(path.join(dist,'game/scene/start.txt'),':example;\nend;');const lic=path.join(kit,'LICENSE');run('package-game.mjs',dist,out,lic);assert.deepEqual(inventory(path.join(out,'webgal/dist')),inventory(dist));assert.equal(fs.readFileSync(path.join(out,'licenses/WebGAL-LICENSE.txt'),'utf8'),fs.readFileSync(lic,'utf8'));assert.throws(()=>run('package-game.mjs',dist,out,lic),/fresh output/);}));
test('index audit ignores untracked content but catches staged credentials and excluded files',()=>fixture(dir=>{const git=(...args)=>execFileSync('git',['-C',dir,...args],{encoding:'utf8',windowsHide:true,stdio:'pipe'});git('init');fs.writeFileSync(path.join(dir,'README.md'),'clean');git('add','README.md');fs.writeFileSync(path.join(dir,'.env'),'TOKEN='+'sk-'+'A'.repeat(32));assert.equal(auditIndex(dir).pass,true);git('add','.env');const report=auditIndex(dir);assert.equal(report.pass,false);assert.ok(report.findings.some(f=>f.category==='credential'));assert.ok(report.findings.some(f=>f.category==='excluded-file'));}));
